(defun load-directory (dir)
  (let ((load-it (lambda (f)
	       (load-file (concat (file-name-as-directory dir) f)))
	     ))
(mapc load-it (directory-files dir nil "\\.el$"))))

(load-directory "~/remacs/lisp")
(load-directory "~/remacs/plugins")
(load-directory "~/remacs/plugins/dired")
(load-directory "~/remacs/plugins/popup-el")
(load-directory "~/remacs/plugins/auto-complete")
(load-directory "~/remacs/plugins/yasnippet")

(require 'dark-theme)
(require 'basic-tools)
(require 'move-text)
(require 'paredit)
(require 'less)
                  
(require 'init-auto-complete)
(require 'init-auto-save)
(require 'init-generic)
(require 'init-multiterm)
(require 'init-linum)
(require 'init-backup)
(require 'init-dired)
(require 'init-indent)
(require 'init-tabbar)
(require 'init-yasnippet)
(require 'init-paredit)
(require 'init-key)
(require 'init-ide)

(provide 'init)
